[package]
name = "event-def"
authors = ["Use Ink <ink@use.ink>"]
version = "0.1.0"
edition = "2024"

[dependencies]
ink = { version = "6.0.0-beta.1", default-features = false }

[lib]
path = "src/lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
]

[package.metadata.ink-lang]
abi = "ink"
