[package]
name = "contract2"
version = "0.1.0"
edition = "2024"
authors = ["Víctor M. González <victor.gonzalez@coinfabrik.com>"]

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = ["ink/std"]
ink-as-dependency = []
e2e-tests = []

[dependencies]
ink = { version = "6.0.0-beta.1", default-features = false }

[dev-dependencies]
ink_e2e = { version = "6.0.0-beta.1" }

[profile.dev]
overflow-checks = false

[profile.release]
overflow-checks = false

[package.metadata.ink-lang]
abi = "ink"
